export enum TransactionStatus {
  PENDING = 'PENDING',
  CANCELLED = 'CANCELLED',
  ACCEPTED = 'ACCEPTED',
  READY_TO_DELIVER = 'READY_TO_DELIVER',
  READY_TO_PICK_UP = 'READY_TO_PICK_UP',
  OUT_OF_DELIVERY = 'OUT_OF_DELIVERY',
  FAILED = 'FAILED',
  COMPLETED = 'COMPLETED',
}
